### PR TITLE
Add Hidden Fates to DB

### PR DESCRIPTION
**Pull request by luongthomas**
This is the Hidden Fates yaml file that is generated from carddb-tools.  This will also include updates to the formats file to include Hidden Fates and UNM to the standard format fields.

### CODE REVIEW

**Comment by axpendix** [comment]
How did you generate this?

**Comment by luongthomas** [comment]
> How did you generate this?

I used the carddb-tool but used the `--export-yaml` option

**Comment by axpendix** [comment]
For a moment of time I forgot I had coded the `copyOf` support in there.

**Comment by axpendix** [comment]
Looks CI errors but it was due to the conflicts in other library and I've fixed it, it'll work fine with the next commit.

**Pull request merged**
