### PR TITLE
Update Standard to match current format

### PR DESCRIPTION
**Pull request by scoot404**
This PR:
- separates the 2018-2019 Standard season into it's own entry _(planning to do this for the other formats as well, looking to coordinate with @axpendix on the necessary things to put for each of these)_
- removed _Sun and Moon_ up to _Crimson Invasion_ from Standard's sets
- currently too tired to write the whole list of cards I moved around but you can see in the commits

### CODE REVIEW

**Comment by axpendix** [comment]
This format.yaml file is currently not used for the in-game system, it's only used for the home page. it uses a legacy syntax to define formats, which I am trying to get rid of. This file will be the source of truth for all formats in near future.

**Comment by scoot404** [comment]
> 
> 
> Hi @scoot404 the given standard format is for 2018-2019 format. We need to add a new entry for 19-20 rather than updating this one.
> Also, `includes` and `excludes` work in tandem.
> If you only want a couple of cards to include from a set, rather than the whole set, you can put that card in `includes` section instead of putting everything else to `excludes`; which is for excluding a couple of cards (such as expanded ban list) from that format.
> You can understand how that works by inspecting https://github.com/axpendix/carddb/blob/master/src/main/java/net/tcgone/carddb/Importer.java#L175

I think I'll go ahead and re-arrange to use "include" for the Shiny Vault, thanks for the thought. Although, I think the Sun and Moon promos should stay as is because there are simply so many promos still in rotation. I'll work on changing Shiny Vault the other way around soon.

> 
> 
> This format.yaml file is currently not used for the in-game system, it's only used for the home page. it uses a legacy syntax to define formats, which I am trying to get rid of. This file will be the source of truth for all formats in near future.

I made this PR with this in mind, thus why I was hoping you could make the necessary changes on the back-end since I don't think I'm able to.

**Comment by scoot404** [comment]
Updated the description to fit the changes made last commit.

**Comment by scoot404** [comment]
Build is failing but after reviewing my commit, I don't believe it is anything on my end. I could be wrong, though. When you're available and it is convenient, please take a look. Changes requested were made so all that'd need done is fixing this build error.

**Pull request closed without merging**
